siteHost: http://inlets.saltbo.cn
storeHost: http://dl.saltbo.cn
database:
  driver: sqlite3
  dsn: zpan.db

provider:
  name: alioss
  bucket: saltbo-zpan-test
  endpoint: https://oss-cn-zhangjiakou.aliyuncs.com
  accessKey: LTAI4FbdK2wD1fe9nknL7YoV
  accessSecret: PFGVwwpAFYaYz7la3vgckr472Rd09u

