language: go
go:
  - 1.13.x
os:
  - linux
  - osx
cache:
  directories:
    - $GOPATH/pkg/mod
dist: trusty
sudo: false
install: true
script:
  - make
  - make test
  - make patch

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    file_glob: true
    file:
      - build/*.tar.gz
    on:
      tags: true